spring:
  application:
    name: shopping-cart
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6553/cart
    username: cart
    password: cart
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true