spring:
  application:
    name: warehouse
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6554/commerce
    username: commerce
    password: commerce
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true