spring:
  application:
    name: payment
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6550/payment
    username: payment
    password: payment
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

payment:
  fee_rate: 0.1

server:
  port: 0

logging:
  level:
    root: INFO
    org:
      zalando:
        logbook: TRACE
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    your.application.package: DEBUG