spring:
  application:
    name: aggregator

kafka:
  bootstrap-servers: localhost:9092
  sensor-topic: telemetry.sensors.v1
  snapshot-topic: telemetry.snapshots.v1
  group-id: aggregator-group
  auto-commit: false

logbook:
  format:
    style: http

logging:
  level:
    org:
      zalando:
        logbook: TRACE